### ISSUE TITLE
Add GA tracking on the site

### ISSUE THREAD

**Issue by tdnvl** [aad-wsux/aisummit#1]
Can you add this in the `<head>`?

`<!-- Global site tag (gtag.js) - Google Analytics -->`
`<script async src="https://www.googletagmanager.com/gtag/js?id=UA-111430295-1"></script>`
`<script>`
`  window.dataLayer = window.dataLayer || [];`
`  function gtag(){dataLayer.push(arguments);}`
`  gtag('js', new Date());`
`  gtag('config', 'UA-111430295-1');`
`</script>`

**Comment by lionetxue** [comment]
Done.
